frappe/ecommerce_integrations

ecommerce_integrations/config/desktop.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_integration_log/ecommerce_integration_log.json, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_integration_log/ecommerce_integration_log.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_integration_log/ecommerce_integration_log_list.js, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_integration_log/test_ecommerce_integration_log.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item.json, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item_list.js, ecommerce_integrations/shopify/connection.py, ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.py, ecommerce_integrations/shopify/doctype/shopify_tax_account/shopify_tax_account.py, ecommerce_integrations/shopify/inventory.py, ecommerce_integrations/shopify/order.py, ecommerce_integrations/shopify/product.py, ecommerce_integrations/shopify/tests/test_connection.py, ecommerce_integrations/shopify/tests/utils.py, ecommerce_integrations/shopify/utils.py, setup.py
=> fix: misc improvements in shopify integration

ecommerce_integrations/shopify/connection.py
When app is not configured and decorator attempts to create a session and it tries to get the password field. This causes the user to log out.
fixes #9
=> fix: don't try to create session if not configured

ecommerce_integrations/shopify/doctype/shopify_tax_account/shopify_tax_account.json, ecommerce_integrations/shopify/order.py
* Add field in child doctype
* Change description to consider specified field first, fallback to default if not available
=> feat: Enable a description text for the final invoice on each tax line setting (#13)

ecommerce_integrations/controllers/scheduling.py, ecommerce_integrations/hooks.py, ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.json, ecommerce_integrations/shopify/inventory.py
Make inventory sync configurable (earlier it was fixed to 1 hour)
Options: 5, 10, 15, 30, 60 minutes.
Note: If `scheduler_tick_interval` is more than 5 minutes then this configuration won't work. The default value is 60 seconds.
=> feat: configurable interval for inventory sync

ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.json, ecommerce_integrations/shopify/tests/utils.py
- removed API key field. 
- added missing labels.
- moved fields to their appropriate place.
-
=> fix(ux): clean up shopify setting page

ecommerce_integrations/shopify/customer.py
It's ignored while syncing, an update should ignore it too.
=> fix: ignore mandatory fields while syncing address

ecommerce_integrations/controllers/customer.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item.py, ecommerce_integrations/shopify/fulfillment.py, ecommerce_integrations/shopify/invoice.py, ecommerce_integrations/shopify/order.py
Both Background jobs and scheduler commit upon successful completion.
These manual commits are unnecessary and can cause inconsistency.
=> fix: remove explicit commits

ecommerce_integrations/hooks.py, ecommerce_integrations/shopify/order.py, ecommerce_integrations/utils/taxation.py
Problem: Item tax templates can cause issues with the computation of taxes.
Solution: There's no way to disable the computation of item tax templates directly, one way to disable them is to use a tax category that's not used by the tax templates.
Ref: https://github.com/frappe/erpnext/blob/b0e77cbd89394a609108768466fef97cb00902bf/erpnext/controllers/taxes_and_totals.py#L57
=> fix: tax category to avoid tax templates

ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_integration_log/ecommerce_integration_log.py, ecommerce_integrations/shopify/order.py, ecommerce_integrations/shopify/tests/utils.py
Problem: If multiple items have different tax rate then applying rates is not gonna give correct tax figures. 
Solution: Apply taxes at actual.
Other problems introduced by this solution:
1. "taxes included in price" won't work out of the box -> solve by calculating basic price = price - tax amount.
2. Tax distribution across items is arbitary. -> solve by specifying exact tax distribution in JSON and asking ERPNext to not recompute it.
=> fix: apply taxes at actuals

ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.py
Since last_inventory_sync field is set to `None` by default, due to
recent changes in `get_single_value` it gets casted to current time.
soln: Initialize a saner default while saving settings, if not available.
=> fix: first inventory sync failing

.github/helper/install.sh, ecommerce_integrations/shopify/order.py
Currently shipping charges assume that it's exclusive of taxes, shopify has global setting "all taxes included in price" which includes shipping too. 
Soln: subtract taxes from shipping lines if order is tax inclusive.
=> fix: handle tax inclusive shipping

ecommerce_integrations/shopify/connection.py
closes https://github.com/frappe/ecommerce_integrations/issues/63 
Migrating users face this problem where old stale webhooks end up causing conflict between two different methods.
=> fix: clear all stale webhooks when registering

ecommerce_integrations/shopify/utils.py
Some users have manually imported or modified these fields. If it's incomplete then migrating them is dangerous and can cause failures.
=> fix: ignore incomplete items while migrating

ecommerce_integrations/hooks.py, ecommerce_integrations/public/js/unicommerce/stock_entry.js, ecommerce_integrations/unicommerce/constants.py, ecommerce_integrations/unicommerce/doctype/unicommerce_settings/unicommerce_settings.json, ecommerce_integrations/unicommerce/doctype/unicommerce_settings/unicommerce_settings.py, ecommerce_integrations/unicommerce/grn.py, ecommerce_integrations/unicommerce/inventory.py, ecommerce_integrations/unicommerce/tests/test_client.py, ecommerce_integrations/unicommerce/tests/utils.py, ecommerce_integrations/unicommerce/utils.py
closes #129 
Change:
1. Setting for enabling GRN using stock entry of material transfer type and add a new transfer type "GRN On Unicommerce"
2. Vendor code configurable in Unicommerce settings. This is a "Fake GRN" only meant for adding stock with batch nos. 
2. Upon submitting a stock entry with GRN on Unicommerce where target warehouse is Unicommerce facility, create a GRN on Unicommerce and map following fields:
- Item Code -> SKU, Item_code
- Qty -> Qty
- Basic rate -> price and MRP
- Stock entry number -> vendor invoice number
- batch no -> batch no
- batch manufacturing date -> manufacturing date
- batch expiry date -> expiry date
Implementation detail:
- Items table gets converted to CSV of "Auto GRN Import" format and posted to bulk import API.
=> feat: Auto GRN settings and stock entry type

ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item.py, ecommerce_integrations/shopify/invoice.py
If the grand total cost on the invoice is 0 it doesn't try to post a payment.
This fixes a problem where ERPNext complains when a payment for 0 is posted.
closes https://github.com/frappe/ecommerce_integrations/issues/162
closes https://github.com/frappe/ecommerce_integrations/issues/157
=> fix: avoid 0 values payment entry and mark items as sales items by default

ecommerce_integrations/shopify/product.py
I have 2 items with the same attribute and it is creating variant items with the same item name.  It's hard to identify the item from attribute value so better to have product name with variant attributes
=> fix: add template name in variant item name

ecommerce_integrations/shopify/customer.py
If the value of key is `None` then `.get` doesn't convert it to `''`. 
`cstr` does exactly that.
=> fix: customer name concatenation

.pre-commit-config.yaml, ecommerce_integrations/shopify/constants.py
No breaking changes that affect integration as per: https://shopify.dev/api/release-notes/2022-04
closes #180 
closes #179
=> fix: bump shopify api version

ecommerce_integrations/unicommerce/grn.py
Uploading difference prices via GRN causes this stupid failure `SKU: sku already present with different Unit Price`
=> fix: dont upload price on unicommerce

ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_repository.py, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api_settings.json, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api_settings.py, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/test_amazon_sp_api_settings.py, ecommerce_integrations/patches.txt, ecommerce_integrations/patches/copy_amazon_single_doc.py
Multiple documents can be added with "is_active" and "enable_sync" checked to sync orders from multiple amazon accounts every hour via hook. To sync orders from a single account, click the "Sync Orders" button.
=> refactor: sync orders from multiple amazon account

.github/workflows/ci.yml, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_integration_log/ecommerce_integration_log.py, ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.js, ecommerce_integrations/unicommerce/api_client.py, ecommerce_integrations/unicommerce/doctype/unicommerce_settings/unicommerce_settings.js, ecommerce_integrations/unicommerce/order.py, ecommerce_integrations/unicommerce/product.py
- support configuring log settings for e-commerce integration logs (v14 only) https://github.com/frappe/frappe/pull/17159 
- show log button on shopify setting page
- better handle SO sync for unicommerce when using in "completed orders" mode
- dont log error when querying for item's existence
=> fix: misc fixes

ecommerce_integrations/shopify/customer.py
**Bug**
In `def _map_address_fields()` phone number validation returned boolean of True or False as a phone. 
**Solved**
- Validated Phone Number
-  Assigned value of phone from Shopify address to the dictionary.
=> fix: phone number mapping in address

ecommerce_integrations/shopify/page/shopify_import_products/shopify_import_products.js
**Issue:**
On the Import Shopify Products page, the SKUs column shows a trailing comma after the last SKU (it shows a comma even it there's only one SKU)
**Before:**
**After:**
**Solution:**
Instead of using the reduce() method to explode the SKUs arrays into separate objects, we can use the map() method and get rid of the trailing comma after the last SKU
=> fix: remove the trailing comma after the last SKU

ecommerce_integrations/shopify/fulfillment.py
Currently, when an order in Shopify is marked as fulfilled, it triggers the creation of a Delivery Note against the synced Sales Order in ERPNext. But, when the Sales Order is missing in ERPNext, this still triggers the creation of a Delivery Note and shows a success message in the Log. Ideally, it should check if Sales Order is present before creating the Delivery Note and if the Sales Order is not present, it should not create the Delivery Note and show the status accordingly in logs.
Implemented an if-else logic block to check if the Sales Order exists before creation of Delivery Note. If the Sales Order is missing, it will show "Invalid: Sales Order not found for syncing delivery note" message in the logs.
=> fix: misleading "success" message for DN when SO doesn't exist

ecommerce_integrations/controllers/inventory.py, ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.json, ecommerce_integrations/shopify/fulfillment.py, ecommerce_integrations/shopify/product.py, ecommerce_integrations/shopify/tests/test_product.py
https://user-images.githubusercontent.com/52111700/196864889-f6e568ba-0aea-4839-9909-8e94483010f9.mp4
=> feat: item variant sync

ecommerce_integrations/shopify/order.py
caused by https://github.com/frappe/ecommerce_integrations/pull/229
```
Traceback (most recent call last):
File "apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 49, in sync_sales_order
create_order(order, setting)
File "apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 61, in create_order
so = create_sales_order(order, setting, company)
File "apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 96, in create_sales_order
taxes = get_order_taxes(shopify_order, setting, items)
File "apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 223, in get_order_taxes
row["item_wise_tax_detail"] = json.dumps(row["item_wise_tax_detail"])
KeyError: 'item_wise_tax_detail'
```
=> fix(shopify): item wise tax detail missing on shipping lines

ecommerce_integrations/shopify/inventory.py
If there are more updates than what can be synced in 5 minutes
background job then there's possibility that inventory sync gets stuck
in infinite loop of never committing the synced data.
By adding commits and batching we can ensure that data is reliably
pushed and committed.
=> perf: batch and commit inventory updates to shopify

ecommerce_integrations/hooks.py, ecommerce_integrations/unicommerce/constants.py, ecommerce_integrations/unicommerce/delivery_note.py, ecommerce_integrations/unicommerce/doctype/unicommerce_settings/unicommerce_settings.json, ecommerce_integrations/unicommerce/doctype/unicommerce_settings/unicommerce_settings.py, ecommerce_integrations/unicommerce/invoice.py, ecommerce_integrations/unicommerce/order.py, ecommerce_integrations/unicommerce/product.py, ecommerce_integrations/unicommerce/tests/test_delivery_note.py
feat: (Uni-commerce) generate Delivery Note and sync item fields
We have implemented the requested functionality as per the client's specifications. 
Specifically, when the designated checkbox is clicked, the system will automatically import Delivery Notes from Uni-commerce into ERPNEXT upon shipment.
https://komododecks.com/recordings/uXlkZvS50jHgA3oxK98y
=> feat: (Uni-commerce) generate Delivery Note and sync item fields

ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api_settings.js
Filters for `Warehouse` and `Account Group` in Amazon SP API Settings.
Before:
After:
=> fix: add filters for `Warehouse` and `Account Group`

ecommerce_integrations/amazon/doctype/amazon_fields_map/amazon_fields_map.json, ecommerce_integrations/amazon/doctype/amazon_fields_map/amazon_fields_map.py, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_repository.py, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api.py, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api_settings.js, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api_settings.json, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api_settings.py, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/test_amazon_sp_api_settings.py, ecommerce_integrations/patches.txt, ecommerce_integrations/patches/set_default_amazon_item_fields_map.py
Issue: Both ASIN and SellerSKU are unique for every item/variant. Some users want to create/find the item based on SellerSKU.
Changes: 
- Added a table to map Amazon (ASIN, SellerSKU and Title) to ERPNext Items. [✅ Create Item If Not Exists]
- Allow the user to find the existing ERPNext Item with Amazon [ASIN/SellerSKU].
- New items will be created while creating a Sales Order based on `Create Item If Not Exists`.
- Sync Orders via RQ Job (4000). 
- Validation for `After Date` to be not more than 30 days old.
- Create customers based on marketplace email (if in the order payload).
docs(draft): https://docs.erpnext.com/docs/user/manual/en/amazon_integration?editWiki=1&wikiPagePatch=3cbed74cc9
=> feat: Amazon - ERPNext Item field map

ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api_settings.py, ecommerce_integrations/patches/set_default_amazon_item_fields_map.py
- forgot to add `frappe.reload_doc` and ignore_validate (to ignore after date validation) in https://github.com/frappe/ecommerce_integrations/pull/260
=> fix(patch): `set_default_amazon_item_fields_map`

ecommerce_integrations/shopify/order.py
**Source / Ref:** 4232
``` python
frappe.db.get_value("Customer", {CUSTOMER_ID_FIELD: shopify_order.get("customer", {}).get("id")}, "name",)
```
If the ID is None, ^ will return a recent customer whose `CUSTOMER_ID_FIELD` is None which causes an incorrect mapping of the Sales Order with Customer.
=> fix: shopify default customer

.github/helper/install.sh, ecommerce_integrations/shopify/order.py
- Itemised sales register in ERPNext generates columns based on the descriptions.
- Due to overriding in description additional columns are added. and there is inconsistency in the report.
Frappe Internal Reference: https://support.frappe.io/app/hd-ticket/1169
=> fix: prioritize user input in tax description

ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.js, ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.json, ecommerce_integrations/shopify/order.py
In countries with USA which has complex taxation for each state, counties etc. it's next to impossible to map all possible tax titles to an account.
This PR adds a fallback account for all sales tax to handle those cases.
Similarly a fallback shipping charge account is introduced.
Note: It's recommended to only use this as last resort, otherwise you might end up posting all entries in single account whereas your accountants might expect you to post in diff accounts. e.g. in India there are only 4-5 legitimate tax account requirements, so it's better not to use default accounts and stick with mapping individual ones.
closes https://github.com/frappe/ecommerce_integrations/issues/194
Internal reference: https://support.frappe.io/helpdesk/tickets/4848
=> feat: specify default tax accounts

ecommerce_integrations/shopify/connection.py, ecommerce_integrations/shopify/constants.py, ecommerce_integrations/shopify/page/shopify_import_products/shopify_import_products.js, requirements.txt
- build: update shopify sdk
- fix: product sync
- fix: Correctly wrap function
=> build: update shopify SDK

ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/test_ecommerce_item.py
SKU is mutable on Shopify, so not a good first metric.
=> fix: Give low priority to SKU

ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.py
Users end up typing complete url with protocol but it doesn't work with
shopify SDK.
Fix: Strip protocol.
=> fix(UX): Correct URL in shopify webhooks

ecommerce_integrations/shopify/fulfillment.py
Earlier the code assumed item can only be used once in order. This
change now uses fifo type assignment of shopify line items to delivery
note line items to only map item code once and then pop it.
=> fix(shopify): handle multiple instance of same item in delivery

ecommerce_integrations/shopify/order.py
Without customer getting the below error while syncing sales orders from Shopify to ERPNext
```
Traceback (most recent call last):
File "apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 55, in sync_sales_order
create_order(order, setting)
File "apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 67, in create_order
so = create_sales_order(order, setting, company)
File "apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 78, in create_sales_order
if customer_id := shopify_order.get("customer", {}).get("id"):
AttributeError: 'NoneType' object has no attribute 'get'
```
=> fix: shopify sync issue without customer
