frappe/ecommerce_integrations

ecommerce_integrations/controllers/inventory.py
This detail would be required for other integrations
=> fix(minor): integration_item_code for inventory sync

.github/helper/install.sh, .github/helper/site_config.json, .github/workflows/ci.yml, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/test_ecommerce_item.py, ecommerce_integrations/hooks.py, ecommerce_integrations/shopify/doctype/shopify_setting/test_shopify_setting.py, ecommerce_integrations/shopify/product.py, ecommerce_integrations/shopify/tests/test_connection.py, ecommerce_integrations/shopify/tests/utils.py
TODO:
~~- [ ] test discovery not picking up all `test_`~~
=> ci: add CI tests

.github/workflows/ci.yml
- Limit branches for running tests
- remove matrix.
=> ci: limit branches for push/pull events + misc.

ecommerce_integrations/shopify/order.py
* Tax Rate in Description field is now rounded
* Using description field on shipping fees and shipping fees taxes
=> fix: Round tax in description and add to shipping calculations (#21)

.flake8, .github/workflows/semgrep.yml, ecommerce_integrations/shopify/product.py, ecommerce_integrations/shopify/tests/utils.py
- Add simple flake8 scanning in semgrep workflow.
- fix reported existing minor issues.
=> ci: flake8

ecommerce_integrations/controllers/customer.py, ecommerce_integrations/shopify/customer.py, ecommerce_integrations/shopify/order.py
* Contact is created on initial sync when having firstname, lastname and mail
* Up on each order, customer address for shipping and billing is updated
* Introduced Shipping Address
=> feat: Enhanced address and contact sync (#14)

.flake8, .github/CODEOWNERS, .github/helper/install.sh, .github/helper/site_config.json, .github/workflows/ci.yml, .github/workflows/semgrep.yml, ecommerce_integrations/controllers/customer.py, ecommerce_integrations/controllers/inventory.py, ecommerce_integrations/controllers/scheduling.py, ecommerce_integrations/controllers/setting.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_integration_log/ecommerce_integration_log.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item.py, ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/test_ecommerce_item.py, ecommerce_integrations/hooks.py, ecommerce_integrations/shopify/connection.py, ecommerce_integrations/shopify/customer.py, ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.json, ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.py, ecommerce_integrations/shopify/doctype/shopify_setting/test_shopify_setting.py, ecommerce_integrations/shopify/doctype/shopify_tax_account/shopify_tax_account.json, ecommerce_integrations/shopify/fulfillment.py, ecommerce_integrations/shopify/inventory.py, ecommerce_integrations/shopify/invoice.py, ecommerce_integrations/shopify/order.py, ecommerce_integrations/shopify/product.py, ecommerce_integrations/shopify/tests/test_connection.py, ecommerce_integrations/shopify/tests/utils.py, ecommerce_integrations/shopify/utils.py
Changelog:
- feature: Configurable inventory sync period
- fix: sync both shipping and billing address. Contributed by @SilentHunter124
- feature: Tax table mapping now allows specifying custom description.  Contributed by @SilentHunter124 
- feature: update existing address when a new address is received.  Contributed by  @SilentHunter124
- ux: improve Shopify setting page.
=> chore(release): merge develop into main

ecommerce_integrations/shopify/utils.py
closes https://github.com/frappe/ecommerce_integrations/issues/45
refer: https://github.com/frappe/erpnext/pull/26700
=> fix: dont check for old settings on v14

.github/helper/install.sh, ecommerce_integrations/unicommerce/doctype/unicommerce_shipment_manifest/unicommerce_shipment_manifest.py, ecommerce_integrations/unicommerce/invoice.py, ecommerce_integrations/unicommerce/utils.py
=> fix: misc unicommerce fixes

ecommerce_integrations/unicommerce/invoice.py
The group warehouse check was being applied on the mapped warehouse which could be a group warehouse. WH allocations can override this and hence this check should apply on the final list of warehouses instead.
=> fix: invoice not submitting with WH allocation

ecommerce_integrations/zenoti/doctype/zenoti_error_logs/zenoti_error_logs.json, ecommerce_integrations/zenoti/utils.py
**Issue-** Log info. are not enough to identify the issue.
**Before -** 
**After -**
=> fix: logging zenoti error message, status code and  title

ecommerce_integrations/hooks.py, ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.json, ecommerce_integrations/shopify/order.py, ecommerce_integrations/utils/price_list.py
=> fix: use dummy price list to avoid clashes

ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.json
closes https://github.com/frappe/ecommerce_integrations/issues/167
docs updated (also present on linked issue above^): https://docs.erpnext.com/docs/v13/user/manual/en/erpnext_integration/shopify_integration
=> fix: update labels for custom app

ecommerce_integrations/unicommerce/grn.py
Reverts frappe/ecommerce_integrations#182
=> chore: grn - upload selling rate

ecommerce_integrations/shopify/page/shopify_import_products/shopify_import_products.js, ecommerce_integrations/shopify/page/shopify_import_products/shopify_import_products.py
Resync exising items in case additional variants have been made in Shopify.
=> feat(shopify): Resync items in bulk import

ecommerce_integrations/shopify/inventory.py
- fix: only log inventory sync failure in single log
- fix: ignore deleted variants from sync
=> fix: handle inventory sync failures

ecommerce_integrations/unicommerce/cancellation_and_returns.py
- fix: Correctly filter existing return order
- fix: check all orders updated in time period
=> fix: CIR returns not happening

.github/workflows/ci.yml, ecommerce_integrations/shopify/constants.py
* fix: bump shopify API version
* ci: node18
=> chore: release 

ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api_settings.js, ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_sp_api_settings.py
=> fix: unable to save `Amazon SP API Settings`

ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.py
closes https://github.com/frappe/ecommerce_integrations/issues/277
=> fix: iterate and fetch all locations

ecommerce_integrations/shopify/order.py
fix: error when there is no billing address is shopify order
=>  fix: error when there is no billing address is shopify order

ecommerce_integrations/shopify/order.py
Backport https://github.com/frappe/ecommerce_integrations/pull/301
=> fix: shopify sync issue without customer
